# CREATE TABLE CLIENT(MS VARCHAR(30) PRIMARY KEY,GST_NUM VARCHAR(20),LOCALITY VARCHAR(50),CITY VARCHAR(20),STATE VARCHAR(20), PINCODE VARCHAR(10), ACC_NUM VARCHAR(20));
# CREATE TABLE CONTAINER(CONTAINER_NUM VARCHAR(25) PRIMARY KEY,VESSEL VARCHAR(30), DESTINATION VARCHAR(30));
# CREATE TABLE SHIPPING_AGENT(INVOICE_NUM VARCHAR(20) PRIMARY KEY, MS VARCHAR(30) REFERENCES CLIENT(MS), DATE DATE);